### ISSUE TITLE
Please upgrade Ember, remove bower dependency

### ISSUE THREAD

**Issue by tylerbrazier** [aboveproperty/ember-drag-drop-polyfill#1]
In Ember v2.13.0, bower has been removed. Please upgrade and remove usages of bower. This addon is the only one in our project that still relies on bower :)

**Comment by sbatson5** [comment]
Have a PR for this. Just waiting on review

**Comment by veelci** [comment]
@sbatson5, I've published a new version with your changes to the npm repository.

**Comment by lypborges** [comment]
I try to use the new version, but it created a bower file inside my project. Should I do something else?

**Comment by sbatson5** [comment]
@lypborges although the update removed the bower dependency from ember, this addon still generates a bower install in the `afterInstall` hook:
https://github.com/aboveproperty/ember-drag-drop-polyfill/blob/a0a0f509b1d21aa23e06c93f0e6e0fb4b720ff59/blueprints/ember-drag-drop-polyfill/index.js

What version of ember are you using? If you are on the latest version, you can now directly install `mobile-drag-drop` (the updated name for drag-drop-polyfill) through npm and don't have to rely on a shim addon.
